### ISSUE TITLE
CLI fails with prompt_toolkit 3

### ISSUE THREAD

**Issue by albireox** [sdss/clu#29]
```
[ERROR]: Traceback (most recent call last):
  File "/Users/albireo/.pyenv/versions/clu/bin/clu", line 2, in <module>
    from clu.__main__ import main
  File "/Users/albireo/Documents/Code/sdss5/clu/python/clu/__main__.py", line 25, in <module>
    prompt_toolkit.eventloop.use_asyncio_event_loop()
AttributeError: module 'prompt_toolkit.eventloop' has no attribute 'use_asyncio_event_loop'
```

See https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/asyncio.html

**Comment by albireox** [comment]
Fixed in 5729a777b2eef1bb1974ff3986bfd6071602d53d
